version: 2
jobs:
  plan:
    docker:
      - image: nicholasjackson/hashicorp-ci:latest
    steps:
      - checkout
      - run:
          command: mkdir plan
      - run:
          name: Terraform plan
          command: |
            export VAULT_TOKEN=$(vault login -token-only -method=github token=${GITHUB_TOKEN}) 
            envconsul -secret aws/creds/aws_readonly -once ./run_terraform.sh plan -out=plan/plan.out
      - persist_to_workspace:
          root: ./
          paths:
            - plan/plan.out
            - .terraform

  apply:
    docker:
      - image: nicholasjackson/hashicorp-ci:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Terraform apply
          command: |
            export VAULT_TOKEN=$(vault login -token-only -method=github token=${GITHUB_TOKEN}) 
            envconsul -secret aws/creds/aws_write -once ./run_terraform.sh apply /tmp/workspace/plan/plan.out

workflows:
  version: 2
  plan-and-apply:
    jobs:
      - plan:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - apply:
          requires:
            - plan
          filters:
            tags:
              only: /.*/
            branches:
              only: /master/

